// Standalone HTML replay bundle generator — PRD §5.
//
// The killer-differentiator feature: a single self-contained HTML
// file that bundles a captured session AND an interactive viewer.
// Open it in any browser, scrub through the timeline, read every
// request body, see the redactions panel — no extension, no
// service, no login. The recipient drags the file into a tab
// and they're done.
//
// Implementation contract:
//   - generateBundle(events, opts) → HTML string.
//   - Output is a complete document: <!doctype html> ... </html>.
//   - All assets (events, viewer JS, CSS) are inlined; the file
//     opens offline without any network requests.
//   - The viewer is vanilla DOM (OQ-M4-D). No framework, no CDN.
//   - Size budget per PRD §5.4: 10 MB typical, 50 MB recording.
//
// Tests: replay-bundle.test.ts.

import { narrate } from '@/lib/narrative';
import type { CapturedEvent } from '@/types/events';

export interface GenerateBundleOptions {
  /** The Hindsight version that produced the bundle. Stamped into
   *  the viewer footer so a recipient can reproduce the producing
   *  environment if needed. */
  appVersion: string;
  /** Optional title shown in the viewer header — falls back to the
   *  origin of the first event when not provided. */
  title?: string;
}

/**
 * Returns the full HTML document for a replay bundle. Caller saves
 * it as a `.html` file and ships it.
 */
export function generateBundle(events: CapturedEvent[], opts: GenerateBundleOptions): string {
  const safeEvents = events.map(sanitizeEvent);
  const safeNarrative = narrate(events);
  const title = opts.title ?? deriveTitle(events);
  const eventsJson = JSON.stringify(safeEvents);
  const narrativeMd = JSON.stringify(safeNarrative);

  // The viewer JS reads window.__HINDSIGHT__ which the inline data
  // block populates. Keeping the data block above the viewer lets
  // the bundle stream-parse incrementally on huge sessions.
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)} — Hindsight replay</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>${VIEWER_CSS}</style>
</head>
<body>
  <header class="topbar">
    <div class="brand"><span class="dot"></span> Hindsight replay</div>
    <div class="title">${escapeHtml(title)}</div>
    <div class="meta"><span id="event-count"></span> · <span id="time-span"></span></div>
  </header>
  <main class="grid">
    <section class="scrubber-wrap" aria-label="Timeline scrubber">
      <div id="scrubber-bars" class="scrubber-bars" aria-hidden="true"></div>
      <input id="scrubber-input" type="range" min="0" max="100" step="1" value="100" aria-label="Jump to time" />
      <div class="scrubber-axis"><span id="scrubber-start"></span><span id="scrubber-end"></span></div>
    </section>
    <details class="narrative-panel" ${safeNarrative ? 'open' : ''}>
      <summary>Session narrative</summary>
      <pre id="narrative-text"></pre>
    </details>
    <section id="event-list" class="list" role="list"></section>
    <aside id="detail-pane" class="detail empty" aria-live="polite">
      <p class="hint">Click an event to inspect it.</p>
    </aside>
  </main>
  <footer class="footnote">Generated by Hindsight v${escapeHtml(opts.appVersion)} · single-file replay (PRD §5)</footer>
  <script>window.__HINDSIGHT__ = { events: ${eventsJson}, narrative: ${narrativeMd} };</script>
  <script>${VIEWER_JS}</script>
</body>
</html>`;
}

function deriveTitle(events: CapturedEvent[]): string {
  for (const e of events) {
    try {
      return new URL(e.url).host;
    } catch {
      // fall through
    }
  }
  return 'Hindsight session';
}

/**
 * Strips fields that can't safely round-trip through JSON.stringify
 * (none today) and gives the sanitizer a hook for future masking
 * passes (PRD §11.2 already applied at capture time, but defense in
 * depth in the export path is cheap). Today it's the identity
 * function — kept for the seam.
 */
function sanitizeEvent(e: CapturedEvent): CapturedEvent {
  return e;
}

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"']/g,
    (c) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
      })[c] ?? c
  );
}

// ---------------------------------------------------------------------------
// Inline viewer assets — kept in this file so the generator stays a
// single dependency. The strings are concatenated into the HTML at
// generation time.
// ---------------------------------------------------------------------------

const VIEWER_CSS = `
:root {
  color-scheme: light dark;
  --bg: #0b1020;
  --surface: #131a2e;
  --surface-2: #1a2340;
  --border: #2a335a;
  --text: #e7ecf5;
  --muted: #8b94b3;
  --danger: #ef4444;
  --warn: #f59e0b;
  --success: #22c55e;
  --accent: #6366f1;
  --mono: ui-monospace, 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace;
  --sans: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
}
@media (prefers-color-scheme: light) {
  :root { --bg: #f7f8fc; --surface: #ffffff; --surface-2: #eef0f6;
    --border: #d6dae6; --text: #0b1020; --muted: #5b6478; --success: #16a34a; }
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text); font: 13px/1.5 var(--sans); }
.topbar { display: flex; align-items: center; gap: 14px; padding: 10px 16px; border-bottom: 1px solid var(--border); background: var(--surface); }
.brand { font-weight: 600; }
.brand .dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: var(--accent); margin-right: 6px; vertical-align: middle; }
.title { font-family: var(--mono); color: var(--muted); }
.meta { margin-left: auto; color: var(--muted); font-size: 12px; }
.grid { display: grid; grid-template-columns: 1fr minmax(320px, 40%); grid-template-rows: auto auto 1fr; gap: 0; height: calc(100vh - 90px); }
.scrubber-wrap { grid-column: 1 / -1; padding: 8px 14px; border-bottom: 1px solid var(--border); background: var(--surface); }
.scrubber-bars { display: flex; align-items: flex-end; gap: 1px; height: 32px; }
.scrubber-bars div { flex: 1; background: var(--accent); opacity: 0.6; border-radius: 1px; min-height: 2px; }
.scrubber-wrap input[type=range] { width: 100%; margin: 4px 0 0; accent-color: var(--accent); }
.scrubber-axis { display: flex; justify-content: space-between; font-family: var(--mono); font-size: 10.5px; color: var(--muted); }
.narrative-panel { grid-column: 1 / -1; padding: 8px 14px; border-bottom: 1px solid var(--border); background: var(--surface-2); }
.narrative-panel summary { cursor: pointer; font-weight: 600; }
.narrative-panel pre { font-family: var(--mono); font-size: 12px; white-space: pre-wrap; margin: 8px 0 0; }
.list { overflow-y: auto; border-right: 1px solid var(--border); }
.item { display: grid; grid-template-columns: 60px 50px 1fr 90px 70px; gap: 8px; padding: 6px 14px; border-bottom: 1px solid var(--border); cursor: pointer; align-items: center; }
.item:hover, .item.active { background: var(--surface-2); }
.item.failed { border-left: 3px solid var(--danger); }
.item.success { border-left: 3px solid transparent; }
.item .status { font-family: var(--mono); font-size: 11px; padding: 2px 6px; border-radius: 4px; background: var(--surface-2); text-align: center; }
.item.failed .status { background: rgba(239,68,68,0.14); color: var(--danger); }
.item .method { font-family: var(--mono); font-size: 11px; color: var(--muted); }
.item .url { font-family: var(--mono); font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.item .time, .item .duration { font-family: var(--mono); font-size: 11px; color: var(--muted); text-align: right; }
.detail { padding: 16px; overflow-y: auto; background: var(--surface); }
.detail.empty { color: var(--muted); }
.detail h3 { margin: 14px 0 6px; font-size: 13px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
.detail pre { font-family: var(--mono); font-size: 12px; background: var(--surface-2); border: 1px solid var(--border); border-radius: 4px; padding: 8px; overflow-x: auto; white-space: pre-wrap; word-break: break-all; max-height: 360px; }
.detail .pill { display: inline-block; padding: 2px 8px; border-radius: 999px; background: var(--surface-2); font-family: var(--mono); font-size: 11px; }
.detail img.screenshot { width: 100%; border: 1px solid var(--border); border-radius: 4px; margin-top: 4px; }
.footnote { padding: 8px 16px; border-top: 1px solid var(--border); color: var(--muted); font-size: 11px; }
`;

const VIEWER_JS = `
(function () {
  var data = window.__HINDSIGHT__ || { events: [], narrative: '' };
  var events = (data.events || []).slice().sort(function (a, b) { return a.timestamp - b.timestamp; });
  var listEl = document.getElementById('event-list');
  var detailEl = document.getElementById('detail-pane');
  var countEl = document.getElementById('event-count');
  var spanEl = document.getElementById('time-span');
  var startEl = document.getElementById('scrubber-start');
  var endEl = document.getElementById('scrubber-end');
  var barsEl = document.getElementById('scrubber-bars');
  var rangeEl = document.getElementById('scrubber-input');
  var narrativeEl = document.getElementById('narrative-text');

  if (narrativeEl) narrativeEl.textContent = data.narrative || '';

  function fmt(ts) {
    var d = new Date(ts);
    function pad(n) { return String(n).padStart(2, '0'); }
    return pad(d.getHours()) + ':' + pad(d.getMinutes()) + ':' + pad(d.getSeconds());
  }
  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function safePath(u) { try { var x = new URL(u); return x.pathname + (x.search || ''); } catch (e) { return u; } }
  function isFailedNetwork(e) {
    if (e.type !== 'network.fetch' && e.type !== 'network.xhr') return false;
    var s = e.data.response.status;
    return s === 0 || s >= 400 || e.data.error != null;
  }

  function row(e) {
    if (e.type === 'network.fetch' || e.type === 'network.xhr') {
      return {
        cls: isFailedNetwork(e) ? 'failed' : 'success',
        status: e.data.response.status || 'ERR',
        method: e.data.request.method,
        url: safePath(e.data.request.url),
        time: fmt(e.timestamp),
        dur: e.data.timing.durationMs + 'ms',
      };
    }
    if (e.type === 'console.error' || e.type === 'console.unhandled') {
      return { cls: 'failed', status: e.type === 'console.unhandled' ? 'UNC' : 'ERR', method: 'LOG', url: e.data.message, time: fmt(e.timestamp), dur: '' };
    }
    if (e.type === 'navigation') {
      return { cls: 'success', status: 'NAV', method: '', url: e.data.toUrl, time: fmt(e.timestamp), dur: '' };
    }
    if (e.type === 'action.click') {
      var n = e.data.target.accessibleName || e.data.target.tag.toLowerCase();
      return { cls: 'success', status: 'CLK', method: '', url: n, time: fmt(e.timestamp), dur: '' };
    }
    if (e.type === 'action.input') {
      var n2 = e.data.target.accessibleName || e.data.target.tag.toLowerCase();
      return { cls: 'success', status: 'INP', method: '', url: n2 + ' = ' + e.data.value, time: fmt(e.timestamp), dur: '' };
    }
    if (e.type === 'screenshot') {
      return { cls: 'success', status: '📷', method: e.data.trigger, url: 'Screenshot at error moment', time: fmt(e.timestamp), dur: '' };
    }
    return { cls: 'success', status: e.type.split('.')[0].toUpperCase().slice(0, 3), method: '', url: e.type, time: fmt(e.timestamp), dur: '' };
  }

  function renderList() {
    var html = events.slice().reverse().map(function (e) {
      var r = row(e);
      return '<div class="item ' + r.cls + '" data-id="' + esc(e.id) + '" role="listitem">'
        + '<div class="status">' + esc(r.status) + '</div>'
        + '<div class="method">' + esc(r.method) + '</div>'
        + '<div class="url" title="' + esc(r.url) + '">' + esc(r.url) + '</div>'
        + '<div class="time">' + esc(r.time) + '</div>'
        + '<div class="duration">' + esc(r.dur) + '</div>'
        + '</div>';
    }).join('');
    listEl.innerHTML = html;
  }

  function renderScrubber() {
    if (events.length < 2) return;
    var start = events[0].timestamp;
    var end = events[events.length - 1].timestamp;
    startEl.textContent = fmt(start);
    endEl.textContent = fmt(end);
    var span = Math.max(1, end - start);
    var BUCKETS = 40;
    var counts = new Array(BUCKETS).fill(0);
    for (var i = 0; i < events.length; i++) {
      var idx = Math.min(BUCKETS - 1, Math.floor(((events[i].timestamp - start) / span) * BUCKETS));
      counts[idx]++;
    }
    var peak = Math.max.apply(null, counts) || 1;
    barsEl.innerHTML = counts.map(function (c) {
      return '<div style="height:' + Math.round(c / peak * 100) + '%"></div>';
    }).join('');
  }

  function renderDetail(e) {
    var lines = [];
    lines.push('<div><span class="pill">' + esc(e.type) + '</span> · ' + esc(new Date(e.timestamp).toLocaleString()) + '</div>');
    if (e.url) lines.push('<h3>Page URL</h3><pre>' + esc(e.url) + '</pre>');
    if (e.type === 'network.fetch' || e.type === 'network.xhr') {
      lines.push('<h3>Request</h3><pre>' + esc(e.data.request.method + ' ' + e.data.request.url) + '</pre>');
      lines.push('<h3>Request headers</h3><pre>' + esc(JSON.stringify(e.data.request.headers, null, 2)) + '</pre>');
      if (e.data.request.body) lines.push('<h3>Request body</h3><pre>' + esc(e.data.request.body) + '</pre>');
      lines.push('<h3>Response</h3><pre>' + esc(e.data.response.status + ' ' + e.data.response.statusText + ' · ' + e.data.timing.durationMs + 'ms') + '</pre>');
      lines.push('<h3>Response headers</h3><pre>' + esc(JSON.stringify(e.data.response.headers, null, 2)) + '</pre>');
      if (e.data.response.body) lines.push('<h3>Response body</h3><pre>' + esc(e.data.response.body) + '</pre>');
    } else if (e.type === 'screenshot' && e.data.dataUrl) {
      lines.push('<h3>Screenshot</h3><img class="screenshot" src="' + esc(e.data.dataUrl) + '" />');
    } else {
      lines.push('<h3>Data</h3><pre>' + esc(JSON.stringify(e.data, null, 2)) + '</pre>');
    }
    if (e.meta && e.meta.redactions && e.meta.redactions.length) {
      lines.push('<h3>Redactions</h3><pre>' + esc(JSON.stringify(e.meta.redactions, null, 2)) + '</pre>');
    }
    detailEl.classList.remove('empty');
    detailEl.innerHTML = lines.join('');
  }

  countEl.textContent = events.length + ' event' + (events.length === 1 ? '' : 's');
  if (events.length > 0) {
    var spanMs = events[events.length - 1].timestamp - events[0].timestamp;
    spanEl.textContent = Math.round(spanMs / 1000) + 's span';
  }
  renderList();
  renderScrubber();
  if (events.length > 0 && events[events.length - 1]) {
    // pre-select latest event for instant "see what just broke" feel
    renderDetail(events[events.length - 1]);
  }

  listEl.addEventListener('click', function (ev) {
    var row = ev.target && ev.target.closest && ev.target.closest('[data-id]');
    if (!row) return;
    var id = row.getAttribute('data-id');
    var found = null;
    for (var i = 0; i < events.length; i++) { if (events[i].id === id) { found = events[i]; break; } }
    if (!found) return;
    listEl.querySelectorAll('.item.active').forEach(function (el) { el.classList.remove('active'); });
    row.classList.add('active');
    renderDetail(found);
  });

  rangeEl.addEventListener('input', function () {
    var pct = Number(rangeEl.value);
    var items = listEl.querySelectorAll('.item');
    if (items.length === 0) return;
    var fromBottom = Math.round(((100 - pct) / 100) * (items.length - 1));
    items[fromBottom].scrollIntoView({ block: 'center' });
  });
})();
`;
